
#description
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


list = [1, 2] 

while list[len(list)-2]+list[len(list)-1] < 4000000:
    list.append(list[len(list)-2]+list[len(list)-1])

print(list)


total = 0

for element in list:
    if element % 2 == 0:
        total += element
    

print(total)


